apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: redis-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50