name: 'Terraform - destroy'

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Destroy'
        required: true
        default: 'destroy'

jobs:
  terraform:
    if: ${{ github.event.inputs.job == 'destroy'}}
    name: 'Terraform - Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
          
      - name: Terraform destroy
        run: terraform destroy -auto-approve